# USM Configuration File
# Target OS: Raspberry Pi OS Trixie (Wayland)

# Display Mode: "single" (turn off internal) or "dual" (keep both on)
USM_MODE="single"

# External display settings (Leave empty "" for automatic)
USM_EXT_RES=""      # Example: "1920x1080@60"
USM_EXT_SCALE="1"   # Example: "1.5"
USM_EXT_POS=""      # Example: "1920,0" (X,Y coordinates for dual mode)

# Enable or disable custom execution hooks ("true" or "false")
USM_ENABLE_HOOKS="false"

# Enable file logging
USM_LOG_ENABLE="true"
